#!/usr/bin/with-contenv bash

set -e

INSYNC_1_DOWNLOAD=${INSYNC_1_DOWNLOAD:-"ms-office"}
INSYNC_2_DOWNLOAD=${INSYNC_2_DOWNLOAD:-"ms-office"}
INSYNC_3_DOWNLOAD=${INSYNC_3_DOWNLOAD:-"ms-office"}
INSYNC_4_DOWNLOAD=${INSYNC_4_DOWNLOAD:-"ms-office"}

# Link Insync config folder to /data
sudo -u abc mkdir -p /data/.config/
sudo -u abc [ -e "/home/abc/.config" ] && rm -fr /home/abc/.config
sudo -u abc ln -s /data/.config /home/abc/.config

# Sanity checks
if [ -z "${INSYNC_1_USERNAME}" ]; then
    echo "ERROR: Please set your \insync_1_USERNAME variable with the Google Drive Account."
    exit 1
fi

if [ -z "${INSYNC_1_AUTH_CODE}" ]; then
    echo "ERROR: No Authentication Code Provided"
    echo "ERROR: Visit https://insynchq.com/auth and follow the steps"
    exit 1
fi

insync start
echo 'Sleeping 10 seconds after starting insync.'
sleep 10s

# Check to see if accounts are unlinked
if insync get_status | grep 'UNLINKED' > dev/null; then 
    echo 'Attempting to authorize accounts.'
    NUM=`printenv | sort | grep '\INSYNC_.*_USERNAME' | wc -l`
    for (( i = 1; i <= $NUM; i++ ))
    do
        INSYNC_USERNAME=INSYNC_${i}_USERNAME
        INSYNC_DOWNLOAD=INSYNC_${i}_DOWNLOAD
        INSYNC_AUTH_CODE=INSYNC_${i}_AUTH_CODE

        sudo -u abc mkdir -p /data/${!INSYNC_USERNAME}
        echo 'Adding account '${!INSYNC_USERNAME}
        sudo -u abc bash -c "exec echo yes | /usr/bin/insync-headless add_account -a ${!INSYNC_AUTH_CODE} -p /data/${!INSYNC_USERNAME} -e ${!INSYNC_DOWNLOAD}"
    done

    echo 'Sleeping 10 seconds to let Insync correctly initialize the new accounts.'
    sleep 10s
fi

# Do selective syncing

NUM=`printenv | sort | grep '\INSYNC_.*_USERNAME' | wc -l`
for (( i = 1; i <= $NUM; i++ ))
do
    INSYNC_USERNAME=INSYNC_${i}_USERNAME
    INSYNC_DISABLE_SYNC=INSYNC_${i}_DISABLE_SYNC
    INSYNC_ENABLE_SYNC=INSYNC_${i}_ENABLE_SYNC

    echo 'Set selective sync for '${!INSYNC_USERNAME}

    # Disable folders
    for folder_id in $(echo ${!INSYNC_DISABLE_SYNC} | sed "s/,/ /g")
    do
        echo "Disable $folder_id"
        insync set_selective_sync ${!INSYNC_USERNAME} ${folder_id} no
    done

    # Enable folders
    for folder_id in $(echo ${!INSYNC_ENABLE_SYNC} | sed "s/,/ /g")
    do
        echo "Enable $folder_id"
        insync set_selective_sync ${!INSYNC_USERNAME} ${folder_id} yes
    done
done

echo 'Sleeping 5 seconds.'
sleep 5s

insync set_autostart yes
insync quit 
